CREATE TABLE "authors" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" VARCHAR(512),
    "age" INTEGER,
    "description" VARCHAR(512),
    "image" VARCHAR(512),
    CONSTRAINT "authors_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "books"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "title" VARCHAR(512),
    "description" VARCHAR(2048),
    "image" VARCHAR(512),
    "author_id" BIGINT,
    CONSTRAINT "book_pkey" PRIMARY KEY ("id")
);
